yolov7:
    onnx_file:     "../weights/yolov7/yolov7-w6.onnx"
    engine_file:   "../weights/yolov7/yolov7-w6.trt"
    type:          "coco"
    mode:          "fp32"    
    batchSize:     1
    imageWidth:    1280
    imageHeight:   1280
    conf_thr:      0.4
    nms_thr:       0.45
    strides:       [8, 16, 32, 64]
    imgMean:       [ 0, 0, 0 ]
    imgStd:        [ 1, 1, 1 ]
