yolov7:
    onnx_file:     "../weights/yolov7/yolov7.onnx"
    engine_file:   "../weights/yolov7/yolov7.trt"
    type:          "coco"
    mode:          "fp32"
    dynamic:       1
    batchSize:     8
    imageWidth:    640
    imageHeight:   640
    conf_thr:      0.25
    nms_thr:       0.45
    strides:       [8, 16, 32]
    imgMean:       [ 0, 0, 0 ]
    imgStd:        [ 1, 1, 1 ]
